### Import needed libraries 

In [9]:
import numpy as np
import gym
import random

### Creating enviroment using Gym

In [10]:
env = gym.make("FrozenLake-v0")

action_space = env.action_space.n
state_size = env.observation_space.n
print(action_space, state_size)

4 16


### Creating Q-Table

In [11]:
qtable = np.zeros((state_size, action_space))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Defining Hyper-parameters

In [55]:
total_episodes = 20000
learning_rate = 0.8
max_steps = 50
gamma = 0.95

# Exploration parameters
epsilon = 0.1
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

### Q-Learning Algorithm

In [56]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_reward = 0
    
    for step in range(max_steps):
        
        # Decide between exploration and explotation
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:])
            
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        qtable[state, action] = qtable[state, action] + learning_rate*(reward + gamma*np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_reward += reward
        
        state = new_state
        
        if done:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_reward)
    
print("Score over time: " + str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.3791
[[3.65576864e-01 4.97742321e-02 6.46931919e-02 2.38570291e-02]
 [7.80088028e-03 2.51441215e-04 1.00966342e-03 1.70502548e-01]
 [7.36804341e-03 4.97481001e-03 3.91694438e-03 3.14061795e-02]
 [2.10609389e-04 4.74879244e-04 4.35536734e-03 2.46013827e-02]
 [5.56421609e-01 1.84175621e-01 2.13924868e-02 4.79883506e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.24774149e-01 1.76203644e-07 5.37759082e-06 1.59626210e-09]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.79868447e-02 7.67168140e-02 2.67377210e-02 5.48766235e-01]
 [5.94086131e-03 7.23578105e-01 4.21242498e-03 1.69963351e-02]
 [6.92245927e-01 4.52543184e-03 4.92494459e-03 5.21438815e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.47389106e-01 3.59715149e-02 9.01351702e-01 2.75399337e-02]
 [6.96611151e-02 9.79678235e-01 5.70998997e-02 1.63270504e-01]
 [0.00000000e+00 0.00000000e+00

In [57]:
env.reset()

for episode in range(10):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
#         env.r0ender()
            
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 33
****************************************************
EPISODE  2
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 21
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 42
****************************************************
EPISODE  5
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 45
****************************************************
EPISODE  6
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 49
****************************************************
EPISODE  7
****************************************************
EPISODE  8
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 6
****************************************************
EPISODE  9
