### Import needed libraries 

In [1]:
import numpy as np
import gym
import random

### Creating enviroment using Gym

In [2]:
env = gym.make("FrozenLake-v0")    # Regular Frozen Lake 4x4
# env = gym.make("FrozenLake8x8-v0")   # Frozen Lake 8x8 

action_space = env.action_space.n     # Number of actions available
state_size = env.observation_space.n  
print(action_space, state_size)

4 16


### Creating Q-Table

In [3]:
qtable = np.zeros((state_size, action_space)) # Initialize Q-Table with zeros
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Defining Hyper-parameters

In [8]:
# General parameters
total_episodes = 15000
learning_rate = 0.8
max_steps = 60
gamma = 0.95

# Exploration parameters
epsilon = 0.1
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

### Q-Learning Algorithm

In [9]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_reward = 0
    
    for step in range(max_steps):
        
        # Decide between exploration and explotation
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:])
            
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action) # Advance one step in the environment
        
        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        qtable[state, action] = qtable[state, action] + learning_rate*(reward + gamma*np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_reward += reward
        
        state = new_state
        
        if done:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) # Modify epsilon
    rewards.append(total_reward)
    
print("Score over time: " + str(sum(rewards)/total_episodes)) # Returns average reward per episode
print(qtable)

Score over time: 0.41286666666666666
[[6.80910927e-02 3.07001554e-01 5.74317069e-02 6.75243076e-02]
 [7.77639491e-03 2.13714749e-03 2.89099613e-03 1.72022953e-01]
 [4.08738649e-01 1.14386932e-03 8.79555530e-03 3.77936552e-02]
 [1.67120973e-02 2.88269754e-03 2.78979217e-03 3.76572575e-02]
 [3.26468114e-01 1.35943447e-02 8.89723385e-05 8.37260703e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.07421431e-05 4.40662686e-08 9.93562103e-02 4.05291136e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.10926295e-02 4.52441466e-02 5.70268316e-03 3.67175391e-01]
 [1.24539763e-02 7.06977429e-01 2.37653238e-02 8.77836442e-02]
 [8.67385984e-01 5.97679701e-01 8.53961360e-03 5.28132799e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.57804331e-02 3.14100116e-02 5.88836492e-01 3.98227033e-03]
 [3.38859172e-01 9.84718673e-01 1.85617607e-01 8.16043259e-01]
 [0.00000000e+00 0

### Play game using Q-Table

In [11]:
env.reset()

for episode in range(10):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        # env.render()    # Un-comment to watch every game step
            
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 34
****************************************************
EPISODE  1
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 7
****************************************************
EPISODE  2
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 35
****************************************************
EPISODE  3
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 15
****************************************************
EPISODE  5
****************************************************
EPISODE  6
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 9
****************************************************
EPISODE  7
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 43
****************************************************
EPISODE  8
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 15
****************************************************
EPISODE  9
  (Down)
SFFF
FHFH
FFFH